global:
  scrape_interval: 5s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor:8080]

  - job_name: nestjs-app
    static_configs:
      - targets: [nestjs-api:4000]
